## Import Packages, Environment Setting

In [1]:
import tensorflow as tf
import tensorflow_probability as tfp

from colorama import Fore, Style

def prepend_tab(target):
    return f'{"":4}{target}'.replace('\n', f'\n{"":4}')

data = [list(range(5 * i, 5 * i + 5)) for i in range(4)]

## Tensor Declaration
We often use $\mathbf{X}$ to denote the feature matrix of the samples, where the where $x_{i,j}$ is the j-th feature of the i-th sample. Note that it is common to have higher dimensional feature tensor.
$$
\mathbf{X}=[x_{i,j}]=\begin{bmatrix}
    x_{1,1} & x_{1,2} & \cdots & x_{1,n}\\
    x_{2,1} & x_{2,2} & \cdots & x_{2,n}\\
    \vdots & \vdots & \ddots & \vdots\\
    x_{m,1} & x_{m,2} & \cdots & x_{m,n}\\
    \end{bmatrix}
$$

In [2]:
print(f'{Fore.RED}tf.eye\n- Create an identity matrix')
print(f'{Style.RESET_ALL}{prepend_tab(tf.eye(4))}\n')
print(f'{Fore.RED}tf.ones\n- Create a tensor full of ones')
print(f'{Style.RESET_ALL}{prepend_tab(tf.ones((4, 5)))}\n')
print(f'{Fore.RED}tf.zeros\n- Create a Tensor full of zeros')
print(f'{Style.RESET_ALL}{prepend_tab(tf.zeros((4, 5)))}\n')
X = tf.ones((4, 5))
print(f'{Fore.RED}tf.ones_like')
print('- Create a tensor full of ones with the same shape of provided matrix')
print(f'{Style.RESET_ALL}{prepend_tab(tf.ones_like(data))}\n')
print(f'{Fore.RED}tf.zeros_like')
print('- Create a tensor full of zeros with the same shape of provided matrix')
print(f'{Style.RESET_ALL}{ prepend_tab(tf.zeros_like(data))}\n')
tf.random.set_seed(0)
X = tf.random.normal((4, 5), mean=0, stddev=0.5)
print(f'{Fore.RED}tf.random.normal')
print('- Createa a tensor with random values from normal distribution')
print(f'{Style.RESET_ALL}{prepend_tab(X)}\n')
tf.random.set_seed(0)
X = tf.random.uniform((4, 5), minval=-1, maxval=1)
print(f'{Fore.RED}tf.random.uniform')
print('- Create a tensor with random values from uniform distribution')
print(f'{Style.RESET_ALL}{prepend_tab(X)}\n')
X = tf.convert_to_tensor(data, dtype=tf.float32)
print(f'{Fore.RED}tf.convert_to_tensor\n- Create a tensor from a Python List or Numpy array')
print(f'{Style.RESET_ALL}{prepend_tab(X)}\n')
Y = tf.identity(X)
print(f'{Fore.RED}tf.identity')
print(f'- Create a tensor with the same content and shape as input{Style.RESET_ALL}')
print(f'{Fore.MAGENTA}{"":4}Input{Style.RESET_ALL}\n{prepend_tab(X)}')
print(f'{Fore.MAGENTA}{"":4}Output{Style.RESET_ALL}\n{prepend_tab(Y)}')
print(f'{Fore.MAGENTA}{"":4}Are input and output tensors the same object?')
print(f'{Style.RESET_ALL}{"":4}{X is Y}{Style.RESET_ALL}')

tf.eye
- Create an identity matrix
    [[1. 0. 0. 0.]
     [0. 1. 0. 0.]
     [0. 0. 1. 0.]
     [0. 0. 0. 1.]]

tf.ones
- Create a tensor full of ones
    [[1. 1. 1. 1. 1.]
     [1. 1. 1. 1. 1.]
     [1. 1. 1. 1. 1.]
     [1. 1. 1. 1. 1.]]

tf.zeros
- Create a Tensor full of zeros
    [[0. 0. 0. 0. 0.]
     [0. 0. 0. 0. 0.]
     [0. 0. 0. 0. 0.]
     [0. 0. 0. 0. 0.]]

tf.ones_like
- Create a tensor full of ones with the same shape of provided matrix
    [[1 1 1 1 1]
     [1 1 1 1 1]
     [1 1 1 1 1]
     [1 1 1 1 1]]

tf.zeros_like
- Create a tensor full of zeros with the same shape of provided matrix
    [[0 0 0 0 0]
     [0 0 0 0 0]
     [0 0 0 0 0]
     [0 0 0 0 0]]

tf.random.normal
- Createa a tensor with random values from normal distribution
    [[ 0.7555313   0.21146102 -0.20984747 -0.5180186  -0.6184139 ]
     [ 0.23513651 -0.00698744  0.59442914  0.30126667  0.29985556]
     [-0.35285595 -0.21648772  0.39681226 -0.3487463  -0.4799166 ]
     [-0.45034844 -0.18040527 -0.11188

## Matrix Properties
Here are some commonly used important properties of Tensor object.

In [3]:
print(f'{Fore.RED}X.device\n- Return the device of the tensor')
print(f'{Style.RESET_ALL}{prepend_tab(X.device)}\n')
print(f'{Fore.RED}X.dtype\n- Return the dtype of the tensor')
print(f'{Style.RESET_ALL}{prepend_tab(X.dtype)}\n')
print(f'{Fore.RED}X.shape\n- Return the shape of the tensor')
print(f'{Style.RESET_ALL}{prepend_tab(X.shape)}')

X.device
- Return the device of the tensor
    /job:localhost/replica:0/task:0/device:CPU:0

X.dtype
- Return the dtype of the tensor
    <dtype: 'float32'>

X.shape
- Return the shape of the tensor
    (4, 5)


## Variable Declaration
Note that the declared Tensor object is constant (i.e the values cannot be changed directly). We often use Tensor object for the feature tensor. We can defined Variable object for mutable tensors. We often use Variable object for the __trainable__ parameters in the neural networks:<br><br>
$$
\mathbf{w}=[w_{j}]=\begin{bmatrix}
    w_{1}\\
    w_{2}\\
    \vdots\\
    w_{n}\\
\end{bmatrix},\;\;\;b=0
$$

In [4]:
w = tf.Variable([[0], [1], [2], [3], [4]], dtype=tf.float32)
print(f'{Fore.RED}tf.Variable\n- Declare a Variable with initial values')
print(f'{Style.RESET_ALL}{prepend_tab(w.numpy())}\n')
print(''.join((
    f'{Fore.RED}V.assign, V.assign_add, V.assign_sub\n- Replace (add, subtract) values',
    f'with the given tensor (only change the input Variable if read_value=True){Style.RESET_ALL}'
)))
print(f'{Fore.MAGENTA}{"":4}Before{Style.RESET_ALL}\n{prepend_tab(w.numpy())}')
w.assign([[4], [3], [2], [1], [0]])
print(f'{Fore.MAGENTA}{"":4}After (assign new values)')
print(f'{Style.RESET_ALL}{prepend_tab(w.numpy())}\n')
print(f'{Fore.RED}V.scatter_nd_update, V.scatter_nd_add, V.scatter_nd_sub')
print(''.join((
    '- Replace (add, subtract) values in the given indices (change the ',
    f'input and also return new Variable){Style.RESET_ALL}'
)))
tf.random.set_seed(0)
indices = tf.constant([[0, 0]])
updates = tf.constant([0], dtype=tf.dtypes.float32)
print(f'{Fore.MAGENTA}{"":4}Before')
print(f'{Style.RESET_ALL}{prepend_tab(w.numpy())}')
updated = w.scatter_nd_update(indices, updates).numpy()
print(f'{Fore.MAGENTA}{"":4}After (replace the first element with 0)')
print(f'{Style.RESET_ALL}{prepend_tab(w.numpy())}')
print(f'{Fore.MAGENTA}{"":4}Returned Variable (replace the first element with 0)?')
print(f'{Style.RESET_ALL}{prepend_tab(updated)}')
print(f'{Fore.MAGENTA}{"":4}Do input and return Variable have the same values?')
print(f'{Style.RESET_ALL}{"":4}{all(w == updated)}')
print(f'{Fore.MAGENTA}{"":4}Are input and return Variable the same object?')
print(f'{Style.RESET_ALL}{"":4}{w is updated}{Style.RESET_ALL}')

tf.Variable
- Declare a Variable with initial values
    [[0.]
     [1.]
     [2.]
     [3.]
     [4.]]

V.assign, V.assign_add, V.assign_sub
- Replace (add, subtract) valueswith the given tensor (only change the input Variable if read_value=True)
    Before
    [[0.]
     [1.]
     [2.]
     [3.]
     [4.]]
    After (assign new values)
    [[4.]
     [3.]
     [2.]
     [1.]
     [0.]]

V.scatter_nd_update, V.scatter_nd_add, V.scatter_nd_sub
- Replace (add, subtract) values in the given indices (change the input and also return new Variable)
    Before
    [[4.]
     [3.]
     [2.]
     [1.]
     [0.]]
    After (replace the first element with 0)
    [[0.]
     [3.]
     [2.]
     [1.]
     [0.]]
    Returned Variable (replace the first element with 0)?
    [[0.]
     [3.]
     [2.]
     [1.]
     [0.]]
    Do input and return Variable have the same values?
    True
    Are input and return Variable the same object?
    False


## Basic Operations on Tensors/Variables

In [5]:
print(f'{Fore.RED}tf.reshape\n- Reshape the Tensor/Variable')
print(f'{Style.RESET_ALL}{prepend_tab(tf.reshape(X, (10, 2)))}\n')
print(f'{Fore.RED}tf.transpose\n- Swap dimension of the Tensor/Variable')
print(f'{Style.RESET_ALL}{prepend_tab(tf.transpose(X, [1, 0]))}\n')
A, B = tf.split(X, 2, axis=0)
print(f'{Fore.RED}tf.split\n- Split the Tensor/Variable into list of Tensors')
print(f'{Fore.MAGENTA}{"":>4}Index: 0\n{Style.RESET_ALL}{prepend_tab(A)}')
print(f'{Fore.MAGENTA}{"":>4}Index: 1\n{Style.RESET_ALL}{prepend_tab(B)}]\n')
print(f'{Fore.RED}tf.concat\n- Concat list of Tensors/Variables along a specific axis')
print(f'{Style.RESET_ALL}{prepend_tab(tf.concat([A, B], axis=0))}\n')
print(f'{Fore.RED}tf.stack\n- Concat list of Tensors/Variables on a new axis')
print(f'{Style.RESET_ALL}{prepend_tab(tf.stack([A, B], axis=0))}\n')
print(f'{Fore.RED}tf.matmul, operators\nArithmetic operations')
print(f'{Style.RESET_ALL}{prepend_tab(tf.matmul(X, w))}\n')
print(f'{Fore.RED}tf.sort\n- Sort the Tensor on a specific axis')
print(f'{Style.RESET_ALL}{prepend_tab(tf.sort(X, axis=1, direction="DESCENDING"))}\n')
print(f'{Fore.RED}tf.argsort\n- Get the order of the Tensor on a specific axis')
print(f'{Style.RESET_ALL}{prepend_tab(tf.argsort(X, axis=1, direction="DESCENDING"))}\n')
print(f'{Fore.RED}tf.reduce_min, tf,reduce_max, tf.reduce_mean, tf_reduce_sum')
print('- Compute min, max, mean and sum of the Tensor')
print(f'{Style.RESET_ALL}{prepend_tab(tf.reduce_min(X, axis=1))}\n')
print(f'{Fore.RED}tfp.stats.percentile\n- Compute the percentile of the Tensor')
print(f'{Style.RESET_ALL}{prepend_tab(tfp.stats.percentile(X, 50, axis=1))}\n')
print(f'{Fore.RED}tf.pow, tf.math.log\n- Compute power or log of Tensor')
print(f'{Style.RESET_ALL}{prepend_tab(tf.pow(X, 2))}\n')
print(f'{Fore.RED}tf.squeeze\n- Remove dimensions with size equals to 1')
print(f'{Style.RESET_ALL}{prepend_tab(tf.squeeze(w))}\n')
print(f'{Fore.RED}tf.expand_dims\n- Expand dimension')
print(f'{Style.RESET_ALL}{prepend_tab(tf.expand_dims(tf.squeeze(w), axis=1))}\n')
print(f'{Fore.RED}tf.where\nReplace values if condition is (not) met')
print(f'{Style.RESET_ALL}{prepend_tab(tf.where(X > 9, tf.zeros_like(X), X))}\n')

tf.reshape
- Reshape the Tensor/Variable
    [[ 0.  1.]
     [ 2.  3.]
     [ 4.  5.]
     [ 6.  7.]
     [ 8.  9.]
     [10. 11.]
     [12. 13.]
     [14. 15.]
     [16. 17.]
     [18. 19.]]

tf.transpose
- Swap dimension of the Tensor/Variable
    [[ 0.  5. 10. 15.]
     [ 1.  6. 11. 16.]
     [ 2.  7. 12. 17.]
     [ 3.  8. 13. 18.]
     [ 4.  9. 14. 19.]]

tf.split
- Split the Tensor/Variable into list of Tensors
    Index: 0
    [[0. 1. 2. 3. 4.]
     [5. 6. 7. 8. 9.]]
    Index: 1
    [[10. 11. 12. 13. 14.]
     [15. 16. 17. 18. 19.]]]

tf.concat
- Concat list of Tensors/Variables along a specific axis
    [[ 0.  1.  2.  3.  4.]
     [ 5.  6.  7.  8.  9.]
     [10. 11. 12. 13. 14.]
     [15. 16. 17. 18. 19.]]

tf.stack
- Concat list of Tensors/Variables on a new axis
    [[[ 0.  1.  2.  3.  4.]
      [ 5.  6.  7.  8.  9.]]
    
     [[10. 11. 12. 13. 14.]
      [15. 16. 17. 18. 19.]]]

tf.matmul, operators
Arithmetic operations
    [[ 10.]
     [ 40.]
     [ 70.]
     [100.]]

tf