## Import Packages, Environment Setting

In [1]:
import tensorflow as tf
import tensorflow_probability as tfp

## Tensor Declaration
We often use $\mathbf{X}$ to denote the feature tensor of the samples. The values in a tensor object is **not mutable**. The following table shows some conventional ways to structure different feature. In this note, we specifically focus on $2$-dimensional tensor for simplicity:

| Data | Feature |
|:---- |:------- |
| Structured | $x_{i,j}$ is the $j$-th feature of the $i$-th sample. |
| Sequential | $x_{i,p,j}$ is the $j$-th feature at position p of the $i$-th sample. |
| Image | $x_{i,v,h,c}$ is the feature at $(h, v)$ pixel at channel $c$ of the $i$-th sample. |
| Video | $x_{i,f,v,h,c}$ is the feature at $(h, v)$ pixel at channel $c$ at frame $f$ of the $i$-th sample. |

## Tensors Declaration

### Identity matrix
`tf.eye(dim)` [API](https://www.tensorflow.org/api_docs/python/tf/eye)

Create an identity matrix

In [2]:
tf.eye(4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

### Tensor of ones

`tf.ones(shape)` [API](https://www.tensorflow.org/api_docs/python/tf/ones)

Create a tensor full of ones with the given shape

In [3]:
tf.ones((4, 5))

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

### Tensor of zeros

`tf.zeros(shape)` [API](https://www.tensorflow.org/api_docs/python/tf/zeros)

Create a tensor full of zeros with the given shape

In [4]:
tf.zeros((4, 5))

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

### Tensor of ones

`tf.ones_like(tensor)` [API](https://www.tensorflow.org/api_docs/python/tf/ones_like) 

Create a tensor full of ones with same shape as the given tensor

In [5]:
X = tf.zeros((4, 5))
tf.ones_like(X)

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

### Tensor of zeros

`tf.zeros_like(tensor)` [API](https://www.tensorflow.org/api_docs/python/tf/zeros_like)

Create a tensor full of zeros with same shape as the given tensor

In [6]:
X = tf.ones((4, 5))
tf.zeros_like(X)

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

### Tensor of values sampled from normal distribution

`tf.random.normal(shape, mean, stddev)` [API](https://www.tensorflow.org/api_docs/python/tf/random/normal)

Create a tensor with values sampled from normal distribution

In [7]:
tf.random.normal((4, 5), 0, 0.5)

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[ 0.5611227 ,  0.00626846, -0.32072705,  0.7328628 , -0.7427286 ],
       [ 0.54453015, -0.7499871 ,  0.21586704, -0.3624112 ,  0.8946143 ],
       [ 0.4947995 ,  0.11716036,  0.66186786, -0.6555192 , -0.0829044 ],
       [-0.11504537, -0.2242107 ,  0.520573  , -0.24790908, -0.55330634]],
      dtype=float32)>

### Tensor of values sampled from uniform distribution

`tf.random.uniform(shape, min, max)` [API](https://www.tensorflow.org/api_docs/python/tf/random/uniform)

Create a tensor with values sampled from uniform distribution

In [8]:
tf.random.normal((4, 5), -1, 1)

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[-1.5792332 , -2.2363796 ,  0.52635705, -1.2432559 , -0.38668972],
       [-2.7568192 , -1.1419466 , -1.2625546 ,  0.3137622 , -0.7589686 ],
       [ 0.5909195 , -1.5370245 , -0.15258765, -0.08633375, -0.30068612],
       [-2.2829576 , -2.1256752 , -1.3503302 , -0.28539228, -0.31904173]],
      dtype=float32)>

### Tensor from Python List or Numpy Array

`tf.convert_to_tensor(ref)` [API](https://www.tensorflow.org/api_docs/python/tf/convert_to_tensor)

Create a tensor with the same shape as the given Python List or Numpy Array

In [9]:
data = [list(range(5 * i, 5 * i + 5)) for i in range(4)]
tf.convert_to_tensor(data, dtype=tf.float32)

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.]], dtype=float32)>

### Duplicate Tensor

`tf.identity(tensor)` [API](https://www.tensorflow.org/api_docs/python/tf/identity)

Create a tensor with the same shape and values as the given Tensor (the created object is different).

In [10]:
X = tf.convert_to_tensor(data)
Y = tf.identity(X)
Y

<tf.Tensor: shape=(4, 5), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])>

In [11]:
X is Y

False

## Tensors Property

`tf.Tensor` [API](https://www.tensorflow.org/api_docs/python/tf/Tensor) 

Note that unlike variables in Python, the tensor and variable with different `dtype` **cannot** perform numerical operations with each other. Therefore, it is recommended to use `tf.float32` for all the Tensors and Variables in most of the cases.


In [12]:
X.device

'/job:localhost/replica:0/task:0/device:CPU:0'

In [13]:
X.dtype

tf.int32

In [14]:
X.shape

TensorShape([4, 5])

In [15]:
X.numpy()

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

## Variables Declaration

Since the values in Tensor objects cannot be changed, we often use Variable object for the **trainable** parameters in the neural networks.

### Variable from Python List, Numpy Array or Tensor

`tf.Variable(init)` [API](https://www.tensorflow.org/api_docs/python/tf/Variable)

In [16]:
tf.Variable([[0], [1], [2], [3], [4]], dtype=tf.float32)

<tf.Variable 'Variable:0' shape=(5, 1) dtype=float32, numpy=
array([[0.],
       [1.],
       [2.],
       [3.],
       [4.]], dtype=float32)>

### Replace all values in Variable

`V.assign(values)`, `V.assign_add(delta)`, `V.assign_sub(delta)`

The provided values need to have the same shape as the Variable object `V`. Note that these operations replace the values and also return a new unread Variable object if `read_value=True`

In [17]:
w = tf.Variable([[0], [1], [2], [3], [4]], dtype=tf.float32)
w.assign([[4], [3], [2], [1], [0]])
w

<tf.Variable 'Variable:0' shape=(5, 1) dtype=float32, numpy=
array([[4.],
       [3.],
       [2.],
       [1.],
       [0.]], dtype=float32)>

### Replace values in specific position in Variable

`V.scatter_nd_update(indices, values)`, `V.scatter_nd_add(indices, delta)`, `V.scatter_nd_sub(indices, delta)`

The provided indices need to have the same dimension as the Variable object `V`. Note that these operations replace the values and also return a new unread Variable object if `read_value=True`


In [18]:
w = tf.Variable([[4], [3], [2], [1], [0]], dtype=tf.float32)
indices = tf.convert_to_tensor([[0, 0]])
updates = tf.convert_to_tensor([0], dtype=tf.float32)
w.scatter_nd_update(indices, updates)
w

<tf.Variable 'Variable:0' shape=(5, 1) dtype=float32, numpy=
array([[0.],
       [3.],
       [2.],
       [1.],
       [0.]], dtype=float32)>

## Common Operations for Tensors and Variables

### Reshape

`tf.reshape(tensor, shape)` [API](https://www.tensorflow.org/api_docs/python/tf/reshape)

Return the given Tensor with the given shape

In [19]:
data = [list(range(5 * i, 5 * i + 5)) for i in range(4)]
X = tf.convert_to_tensor(data, dtype=tf.float32)
tf.reshape(X, (10, 2))

<tf.Tensor: shape=(10, 2), dtype=float32, numpy=
array([[ 0.,  1.],
       [ 2.,  3.],
       [ 4.,  5.],
       [ 6.,  7.],
       [ 8.,  9.],
       [10., 11.],
       [12., 13.],
       [14., 15.],
       [16., 17.],
       [18., 19.]], dtype=float32)>

### Transpose

`tf.transpose(tensor, [dim_1, dim_2, ...])` [API](https://www.tensorflow.org/api_docs/python/tf/transpose)

Return the given Tensor with swapped axes.  The original axes are denoted as `0, 1, 2, ...` . The provided permutation use the index in the Python List to indicate the new order of the original axes. For instance `[1, 0]` suggests putting the second axis of the original Tensor to the first one, and putting the first axis to the second one.

In [20]:
data = [list(range(5 * i, 5 * i + 5)) for i in range(4)]
X = tf.convert_to_tensor(data, dtype=tf.float32)
tf.transpose(X, [1, 0])

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[ 0.,  5., 10., 15.],
       [ 1.,  6., 11., 16.],
       [ 2.,  7., 12., 17.],
       [ 3.,  8., 13., 18.],
       [ 4.,  9., 14., 19.]], dtype=float32)>

### Split

`tf.split(tensor, num, axis)` [API](https://www.tensorflow.org/api_docs/python/tf/split)

Return a list consists of `num` of Tensor that split from the given Tensor in the given `axis`

In [21]:
data = [list(range(5 * i, 5 * i + 5)) for i in range(4)]
X = tf.convert_to_tensor(data)
Y = tf.split(X, 2, axis=0)
Y[0]

<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])>

In [22]:
Y[1]

<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])>

### Concatenate

`tf.concat(list, axis)` [API](https://www.tensorflow.org/api_docs/python/tf/concat)

Return the concatenation of list of Tensors along the given `axis`

In [23]:
a = tf.convert_to_tensor([[0., 1., 2., 3., 4.], [5., 6., 7., 8., 9.]])
b = tf.convert_to_tensor([[10., 11., 12., 13., 14.], [15., 16., 17., 18., 19.]])
tf.concat([a, b], axis=0)

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.]], dtype=float32)>

### Stack

`tf.stack(list, axis)` [API](https://www.tensorflow.org/api_docs/python/tf/stack)

Return the concatenation of list of Tensors along the given `axis`. Note the difference in shape compare to `tf.concat`.

In [24]:
a = tf.convert_to_tensor([[0., 1., 2., 3., 4.], [5., 6., 7., 8., 9.]])
b = tf.convert_to_tensor([[10., 11., 12., 13., 14.], [15., 16., 17., 18., 19.]])
tf.stack([a, b], axis=0)

<tf.Tensor: shape=(2, 2, 5), dtype=float32, numpy=
array([[[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.]],

       [[10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]]], dtype=float32)>

### Squeeze

`tf.squeeze(tensor)` [API](https://www.tensorflow.org/api_docs/python/tf/squeeze)

Return the tensor that remove the dimensions with only one element.

In [25]:
X = tf.convert_to_tensor([[0.], [1.], [2.], [3.], [4.]])
tf.squeeze(X)

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([0., 1., 2., 3., 4.], dtype=float32)>

### Expand Dimension

`tf.expand_dim(tensor, axis)` [API](https://www.tensorflow.org/api_docs/python/tf/expand_dims)

Return the tensor that expand the dimensions on the given `axis`.

In [26]:
X = tf.convert_to_tensor([0., 1., 2., 3., 4.])
tf.expand_dims(X, axis=1)

<tf.Tensor: shape=(5, 1), dtype=float32, numpy=
array([[0.],
       [1.],
       [2.],
       [3.],
       [4.]], dtype=float32)>

### Assign values for given condition

`tf.where(condition, x, y)` [API](https://www.tensorflow.org/api_docs/python/tf/where)

Create a Tensor with values equals to `x` if the condition is met for a specific position. The values equals to `y` if the condition is not met. Note that the shape for `x`, `y`the Tensor used in the condition need to be the same.

In [27]:
data = [list(range(5 * i, 5 * i + 5)) for i in range(4)]
X = tf.convert_to_tensor(data, dtype=tf.float64)
tf.where(X > 10, tf.zeros_like(X), tf.pow(X, 2))

<tf.Tensor: shape=(4, 5), dtype=float64, numpy=
array([[  0.,   1.,   4.,   9.,  16.],
       [ 25.,  36.,  49.,  64.,  81.],
       [100.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.]])>

### Arithmetic Operations

`tf.matmul(operand_1, operand_2)` , `operators` [API](https://www.tensorflow.org/api_docs/python/tf/linalg/matmul)

The arithmetic operators performed elementwise operations, so the operands need to share the same shape.

In [28]:
data = [list(range(5 * i, 5 * i + 5)) for i in range(4)]
X = tf.convert_to_tensor(data, dtype=tf.float32)
w = tf.Variable([[4], [3], [2], [1], [0]], dtype=tf.float32)
tf.matmul(X, w)

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[ 10.],
       [ 60.],
       [110.],
       [160.]], dtype=float32)>

### Power and Log-transformation

`tf.pow(tensor, power)` [API](https://www.tensorflow.org/api_docs/python/tf/math/pow), `tf.math.log(tensor)` [API](https://www.tensorflow.org/api_docs/python/tf/math/log)

Return the Tensor after exponential natural log transformation.

In [29]:
data = [list(range(5 * i, 5 * i + 5)) for i in range(4)]
X = tf.convert_to_tensor(data, dtype=tf.float64)
tf.pow(X, 2)

<tf.Tensor: shape=(4, 5), dtype=float64, numpy=
array([[  0.,   1.,   4.,   9.,  16.],
       [ 25.,  36.,  49.,  64.,  81.],
       [100., 121., 144., 169., 196.],
       [225., 256., 289., 324., 361.]])>

### Basic Statistics

`tf.reduce_min(tensor, axis)` [API](https://www.tensorflow.org/api_docs/python/tf/math/reduce_min), `tf.reduce_max(tensor, axis)` [API](https://www.tensorflow.org/api_docs/python/tf/math/reduce_max), `tf.reduce_sum(tensor, axis)` [API](https://www.tensorflow.org/api_docs/python/tf/math/reduce_sum), `tf.reduce_mean(tensor, axis)` [API](https://www.tensorflow.org/api_docs/python/tf/math/reduce_mean)

Compute the statistics along with the given `axis`. If `axis` is not provided, compute the statistics considering the entire Tensor.

In [30]:
data = [list(range(5 * i, 5 * i + 5)) for i in range(4)]
X = tf.convert_to_tensor(data, dtype=tf.float32)
tf.reduce_mean(X, 1)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 2.,  7., 12., 17.], dtype=float32)>

### Percentile

`tfp.stats.percentile(tensor, percentile, axis)` [API](https://www.tensorflow.org/probability/api_docs/python/tfp/stats/percentile)

Compute the statistics along with the given `axis`. If `axis` is not provided, compute the statistics considering the entire Tensor.

In [31]:
data = [list(range(5 * i, 5 * i + 5)) for i in range(4)]
X = tf.convert_to_tensor(data, dtype=tf.float32)
tfp.stats.percentile(X, 50, axis=1)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 2.,  7., 12., 17.], dtype=float32)>

### Sort

`tf.sort(tensor, axis, direction)` [API](https://www.tensorflow.org/api_docs/python/tf/sort)

Return the sorted tensor on the give `axis`. Note that the original tensor remains unchanged.

In [32]:
data = [list(range(5 * i, 5 * i + 5)) for i in range(4)]
X = tf.convert_to_tensor(data, dtype=tf.float32)
tf.sort(X, 0, 'DESCENDING')

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[15., 16., 17., 18., 19.],
       [10., 11., 12., 13., 14.],
       [ 5.,  6.,  7.,  8.,  9.],
       [ 0.,  1.,  2.,  3.,  4.]], dtype=float32)>

## Order

`tf.argsort(tensor, axis, direction)` [API](https://www.tensorflow.org/api_docs/python/tf/argsort)

Return the sorted order of each element in tensor on the give `axis`. 

In [33]:
data = [list(range(5 * i, 5 * i + 5)) for i in range(4)]
X = tf.convert_to_tensor(data, dtype=tf.float32)
tf.argsort(X, 0, 'DESCENDING')

<tf.Tensor: shape=(4, 5), dtype=int32, numpy=
array([[3, 3, 3, 3, 3],
       [2, 2, 2, 2, 2],
       [1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0]])>